/**
 * Authoritative Local IndexedDB Engine for SilverHands
 * 
 * Provides typed, single-source-of-truth browser persistence for:
 * - users & consumer accounts
 * - creator profiles
 * - local sessions
 * - master videos (private)
 * - video versions (draft / published)
 * - video blobs (raw media storage)
 * - public posts (consumer-visible published items)
 * - products & appointments
 */

const DB_NAME = 'SilverHandsLocalDB';
const DB_VERSION = 1;

export interface DBUser {
  id: string; // e.g. usr_12345
  username: string;
  email?: string;
  phone?: string;
  role: 'senior' | 'buyer' | 'guardian' | 'consumer';
  passwordHash?: string;
  voicePin?: string;
  createdAt: string;
  updatedAt: string;
}

export interface DBCreatorProfile {
  id: string; // e.g. prof_usr_12345
  userId: string;
  displayName: string;
  skill?: string;
  skills?: Array<{ name: string; type?: 'primary' | 'additional'; experience_years?: number | null }>;
  experienceYears?: number | null;
  location?: string;
  locality?: string;
  city?: string;
  state?: string;
  lat?: number;
  lng?: number;
  language?: string;
  services?: string[];
  availability?: string | null;
  bio?: string;
  photoUrl?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface DBSession {
  id: string; // e.g. sess_12345
  userId: string;
  role: 'senior' | 'buyer' | 'guardian' | 'consumer';
  username: string;
  token: string;
  createdAt: string;
  expiresAt: string;
}

export interface DBMasterVideo {
  id: string; // e.g. mvid_12345
  creatorId: string;
  creatorName: string;
  title: string;
  description?: string;
  sourceType: 'RECORDED' | 'UPLOADED';
  durationSeconds: number;
  mimeType: string;
  blobId: string; // references video_blobs store
  status: 'RECORDED' | 'PROCESSED';
  createdAt: string;
  updatedAt: string;
}

export interface DBVideoVersion {
  id: string; // e.g. ver_mvid_12345_1
  videoId: string; // references master video id
  creatorId: string;
  creatorName: string;
  versionNumber: number;
  title: string;
  hookText?: string;
  durationSeconds: number;
  mimeType: string;
  blobId?: string; // references video_blobs store
  storagePath?: string; // relative backend path if generated by backend
  status: 'DRAFT' | 'PROCESSING' | 'FAILED' | 'PUBLISHED';
  publishedAt?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface DBVideoBlob {
  id: string; // e.g. blob_12345
  blob: Blob;
  mimeType: string;
  sizeBytes: number;
  createdAt: string;
}

export interface DBPublicPost {
  id: string; // e.g. post_ver_12345
  videoVersionId: string;
  videoId: string;
  creatorId: string;
  creatorName: string;
  title: string;
  description?: string;
  category?: string;
  durationSeconds: number;
  views: number;
  likes: number;
  publishedAt: string;
}

export interface DBProduct {
  id: string;
  creatorId: string;
  creatorName: string;
  title: string;
  description: string;
  price: number;
  category: string;
  stock: number;
  isActive: boolean;
  imageUrl?: string;
  lat?: number;
  lng?: number;
  locality?: string;
  createdAt: string;
}

export interface DBLiveSession {
  id: string;
  creatorId: string;
  creatorName: string;
  title: string;
  description: string;
  meetUrl: string;
  viewerCount: number;
  isLive: boolean;
  startedAt: string;
}

export interface DBAppointment {
  id: string;
  providerId: string;
  providerName: string;
  consumerId: string;
  consumerName: string;
  slot: string;
  price: number;
  status: 'confirmed' | 'completed' | 'cancelled';
  bookedAt: string;
}

class LocalDatabase {
  private dbPromise: Promise<IDBDatabase> | null = null;

  public getDB(): Promise<IDBDatabase> {
    if (typeof window === 'undefined') {
      return Promise.reject(new Error('IndexedDB is only accessible in browser environment.'));
    }

    if (!this.dbPromise) {
      this.dbPromise = new Promise((resolve, reject) => {
        const request = window.indexedDB.open(DB_NAME, DB_VERSION);

        request.onupgradeneeded = (event) => {
          const db = request.result;

          // 1. users
          if (!db.objectStoreNames.contains('users')) {
            const userStore = db.createObjectStore('users', { keyPath: 'id' });
            userStore.createIndex('username', 'username', { unique: false });
            userStore.createIndex('email', 'email', { unique: false });
            userStore.createIndex('role', 'role', { unique: false });
          }

          // 2. profiles
          if (!db.objectStoreNames.contains('profiles')) {
            const profStore = db.createObjectStore('profiles', { keyPath: 'id' });
            profStore.createIndex('userId', 'userId', { unique: true });
            profStore.createIndex('displayName', 'displayName', { unique: false });
          }

          // 3. sessions
          if (!db.objectStoreNames.contains('sessions')) {
            const sessStore = db.createObjectStore('sessions', { keyPath: 'id' });
            sessStore.createIndex('userId', 'userId', { unique: false });
            sessStore.createIndex('token', 'token', { unique: true });
          }

          // 4. videos (Master)
          if (!db.objectStoreNames.contains('videos')) {
            const vidStore = db.createObjectStore('videos', { keyPath: 'id' });
            vidStore.createIndex('creatorId', 'creatorId', { unique: false });
            vidStore.createIndex('status', 'status', { unique: false });
          }

          // 5. video_versions
          if (!db.objectStoreNames.contains('video_versions')) {
            const verStore = db.createObjectStore('video_versions', { keyPath: 'id' });
            verStore.createIndex('videoId', 'videoId', { unique: false });
            verStore.createIndex('creatorId', 'creatorId', { unique: false });
            verStore.createIndex('status', 'status', { unique: false });
          }

          // 6. video_blobs
          if (!db.objectStoreNames.contains('video_blobs')) {
            db.createObjectStore('video_blobs', { keyPath: 'id' });
          }

          // 7. posts (Consumer-facing public posts)
          if (!db.objectStoreNames.contains('posts')) {
            const postStore = db.createObjectStore('posts', { keyPath: 'id' });
            postStore.createIndex('videoVersionId', 'videoVersionId', { unique: true });
            postStore.createIndex('creatorId', 'creatorId', { unique: false });
          }

          // 8. products
          if (!db.objectStoreNames.contains('products')) {
            const prodStore = db.createObjectStore('products', { keyPath: 'id' });
            prodStore.createIndex('creatorId', 'creatorId', { unique: false });
            prodStore.createIndex('category', 'category', { unique: false });
          }

          // 9. live_sessions
          if (!db.objectStoreNames.contains('live_sessions')) {
            const liveStore = db.createObjectStore('live_sessions', { keyPath: 'id' });
            liveStore.createIndex('creatorId', 'creatorId', { unique: false });
          }

          // 10. appointments
          if (!db.objectStoreNames.contains('appointments')) {
            const apptStore = db.createObjectStore('appointments', { keyPath: 'id' });
            apptStore.createIndex('providerId', 'providerId', { unique: false });
            apptStore.createIndex('consumerId', 'consumerId', { unique: false });
          }
        };

        request.onsuccess = () => resolve(request.result);
        request.onerror = () => {
          this.dbPromise = null;
          reject(request.error);
        };
      });
    }

    return this.dbPromise;
  }

  // ── Generic Store Operations ──────────────────────────────────────────────

  public async get<T>(storeName: string, key: IDBValidKey): Promise<T | null> {
    const db = await this.getDB();
    return new Promise((resolve, reject) => {
      const tx = db.transaction(storeName, 'readonly');
      const store = tx.objectStore(storeName);
      const req = store.get(key);
      req.onsuccess = () => resolve(req.result || null);
      req.onerror = () => reject(req.error);
    });
  }

  public async getAll<T>(storeName: string): Promise<T[]> {
    const db = await this.getDB();
    return new Promise((resolve, reject) => {
      const tx = db.transaction(storeName, 'readonly');
      const store = tx.objectStore(storeName);
      const req = store.getAll();
      req.onsuccess = () => resolve(req.result || []);
      req.onerror = () => reject(req.error);
    });
  }

  public async getByIndex<T>(storeName: string, indexName: string, value: IDBValidKey): Promise<T[]> {
    const db = await this.getDB();
    return new Promise((resolve, reject) => {
      const tx = db.transaction(storeName, 'readonly');
      const store = tx.objectStore(storeName);
      const index = store.index(indexName);
      const req = index.getAll(value);
      req.onsuccess = () => resolve(req.result || []);
      req.onerror = () => reject(req.error);
    });
  }

  public async put<T>(storeName: string, value: T): Promise<T> {
    const db = await this.getDB();
    return new Promise((resolve, reject) => {
      const tx = db.transaction(storeName, 'readwrite');
      const store = tx.objectStore(storeName);
      const req = store.put(value);
      req.onsuccess = () => resolve(value);
      req.onerror = () => reject(req.error);
    });
  }

  public async delete(storeName: string, key: IDBValidKey): Promise<void> {
    const db = await this.getDB();
    return new Promise((resolve, reject) => {
      const tx = db.transaction(storeName, 'readwrite');
      const store = tx.objectStore(storeName);
      const req = store.delete(key);
      req.onsuccess = () => resolve();
      req.onerror = () => reject(req.error);
    });
  }

  public async clear(storeName: string): Promise<void> {
    const db = await this.getDB();
    return new Promise((resolve, reject) => {
      const tx = db.transaction(storeName, 'readwrite');
      const store = tx.objectStore(storeName);
      const req = store.clear();
      req.onsuccess = () => resolve();
      req.onerror = () => reject(req.error);
    });
  }
}

export const localDB = new LocalDatabase();
